// <auto-generated />
using System;
using DiarioAdestramento.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiarioAdestramento.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260721204918_PrimeiraMigration")]
    partial class PrimeiraMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("DiarioAdestramento.Models.Cachorro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Idade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Raca")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cachorros");
                });

            modelBuilder.Entity("DiarioAdestramento.Models.Local", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Obs")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TipoDoLocal")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Locais");
                });

            modelBuilder.Entity("DiarioAdestramento.Models.RegistroClima", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CondicaoTempo")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Momento")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Precipitacao")
                        .HasColumnType("REAL");

                    b.Property<int>("SessaoTreinoId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TemperaturaCelsius")
                        .HasColumnType("REAL");

                    b.Property<double?>("VelocidadeDeVento")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("SessaoTreinoId");

                    b.ToTable("RegistrosClima");
                });

            modelBuilder.Entity("DiarioAdestramento.Models.SessaoTreino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CachorroId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("HoraFim")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("TEXT");

                    b.Property<int>("LocalId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Obs")
                        .HasColumnType("TEXT");

                    b.Property<string>("OqueFoiTreinado")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecomepensasUtilizadas")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TempoResposta")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CachorroId");

                    b.HasIndex("LocalId");

                    b.ToTable("SessoesTreino");
                });

            modelBuilder.Entity("DiarioAdestramento.Models.RegistroClima", b =>
                {
                    b.HasOne("DiarioAdestramento.Models.SessaoTreino", "Sessao")
                        .WithMany("RegistrosClima")
                        .HasForeignKey("SessaoTreinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sessao");
                });

            modelBuilder.Entity("DiarioAdestramento.Models.SessaoTreino", b =>
                {
                    b.HasOne("DiarioAdestramento.Models.Cachorro", "Cachorro")
                        .WithMany("Sessao")
                        .HasForeignKey("CachorroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiarioAdestramento.Models.Local", "Local")
                        .WithMany("Sessao")
                        .HasForeignKey("LocalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cachorro");

                    b.Navigation("Local");
                });

            modelBuilder.Entity("DiarioAdestramento.Models.Cachorro", b =>
                {
                    b.Navigation("Sessao");
                });

            modelBuilder.Entity("DiarioAdestramento.Models.Local", b =>
                {
                    b.Navigation("Sessao");
                });

            modelBuilder.Entity("DiarioAdestramento.Models.SessaoTreino", b =>
                {
                    b.Navigation("RegistrosClima");
                });
#pragma warning restore 612, 618
        }
    }
}
